Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -42,10 +42,26 @@ jobs:
       with:
         name: coverage-report
         path: cov.html
-    - name: Fail if test coverage is less than 70%
-      if: ${{ steps.test.outputs.coverage < 70 && github.event.type == 'push' }}
+    - name: Calculate Test Coverage
+      id: coverage
       run: |
-        exit 1
+        coverage=$(grep -E -o "[0-9]+\.[0-9]+" index.html | head -1)
+        echo "Coverage: $coverage%"
+        echo "::set-output name=coverage::$coverage"
+    - name: Check Test Coverage
+      run: |
+        coverage=${{ steps.coverage.outputs.coverage }}
+        if [[ -n "$coverage" && $(echo "$coverage >= 70" | bc -l) -eq 1 ]]; then
+          echo "Test coverage is greater than or equal to 70%"
+        else
+          echo "Test coverage is less than 70%. Aborting the workflow."
+          exit 1
+        fi
+
+   
+
+
+
 
    
     
